name: pnpm lib package

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: echo lib
        run: git diff --quiet HEAD^ HEAD -- "./pnpm/packages/lib" || echo "Testing in lib"
