name: pnpm lib package

on:
  push:
    branches: main
    paths: "/pnpm/packages/lib"
  pull_request:
    branches: main
    paths: "/pnpm/packages/lib"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing"
