name: pnpm lib package

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo lib
        run: git diff --quiet HEAD^ HEAD -- "./packages/lib" || echo "Testing in lib"
