name: turbo checking

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install node
        uses: actions/setup-node@v3

      - name: Change folder
        run: cd ./turbo

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install packages
        run: pnpm install

      - name: Typecheck
        run: pnpx turbo typecheck --filter=[HEAD^2]
