name: turbo checking

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@v3

      - name: Install pnpm
        run: npm install -g pnpm
        working-directory: turbo/

      - name: Install packages
        run: pnpm install
        working-directory: turbo/

      - name: Typecheck
        run: pnpx turbo typecheck --filter=[HEAD^2]
        working-directory: turbo/
